plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "me.modmuss50.mod-publish-plugin"
}
mod_version = "${mod_version}${fabricVersionAppend}"
version = mod_version

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.forge_config_api_port_version}"

}

loom {
    def aw = project(':common').file("src/main/resources/META-INF/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
        datagen {
            client()
            setConfigName('Fabric Datagen')
            ideConfigGenerated(true)
            runDir('runs/datagen')
            vmArg("-Dfabric-api.datagen")
            vmArg("-Dfabric-api.datagen.output-dir=${project(':common').file('src/generated/resources')}")
            vmArg("-Dfabric-api.datagen.modid=${mod_id}")
        }
    }
    repositories {
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
        maven {
            url "https://api.modrinth.com/maven"
            content {
                includeGroup "maven.modrinth"
            }
        }
        flatDir {
            dir 'libs'
        }
    }
    dependencies {
        modImplementation "curse.maven:jade-324717:6011268"
        modImplementation "curse.maven:jei-238222:5846878"

        implementation("net.jodah:typetools:0.6.3")

        modImplementation "curse.maven:glitchcore-955399:5660741"
        modImplementation "curse.maven:serene-seasons-291874:5753502"

        modCompileOnly "curse.maven:continuity-531351:5962881"

        modRuntimeOnly "maven.modrinth:sodium:u1OEbNKx"
    }

}

sourceSets.main.resources { srcDir 'src/generated/resources' }

