plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id "me.modmuss50.mod-publish-plugin"
}
mod_version = "${mod_version}${fabricVersionAppend}"
version = mod_version

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${project.forge_config_api_port_version}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

loom {
    def aw = project(':common').file("src/main/resources/META-INF/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
        datagen {
            client()
            setConfigName('Fabric Datagen')
            ideConfigGenerated(true)
            runDir('runs/datagen')
            vmArg("-Dfabric-api.datagen")
            vmArg("-Dfabric-api.datagen.output-dir=${project(':common').file('src/generated/client/resources')}")
            vmArg("-Dfabric-api.datagen.modid=${mod_id}")
        }
    }
    repositories {
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
        maven {
            url "https://api.modrinth.com/maven"
            content {
                includeGroup "maven.modrinth"
            }
        }
        maven {
            name = "BlameJared"
            url = "https://maven.blamejared.com"
        }
        flatDir {
            dir 'libs'
        }
    }
    dependencies {
        implementation "maven.modrinth:jade:ue8CO97w"
        implementation "mezz.jei:jei-26.2-fabric:30.24.0.176"

        implementation("net.jodah:typetools:0.6.3")

        implementation "maven.modrinth:glitchcore:SDUCBYRU"
        implementation "maven.modrinth:serene-seasons:13sXhUkI"

        compileOnly "maven.modrinth:continuity:mgUN5Xz2"

        runtimeOnly "maven.modrinth:sodium:2Yom1N68"
    }

}

sourceSets.main.resources { srcDir 'src/generated/resources' }

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

tasks.named('compileJava', JavaCompile) {
    options.compilerArgs << '-Xmaxerrs' << '10000'
}
