plugins {
    id 'multiloader-common'
}

configurations {
    commonJava{
        canBeResolved = true
    }
    commonResources{
        canBeResolved = true
    }
}

dependencies {
    compileOnly(project(':common')) {
        capabilities {
            requireCapability "$group:$mod_id"
        }
    }
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(configurations.commonJava)
    if (project.name != 'fabric') {
        source(configurations.commonJava)
    }
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(configurations.commonJava)
    if (project.name != 'fabric') {
        source(configurations.commonJava)
    }
}

tasks.named('sourcesJar', Jar) {
    dependsOn(configurations.commonJava)
    if (project.name != 'fabric') {
        from(configurations.commonJava)
    }
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

pluginManager.withPlugin('me.modmuss50.mod-publish-plugin') {
    def isFabric = project.name == 'fabric'
    def loaderName = isFabric ? 'Fabric' : 'NeoForge'
    def changelogFile = file("../${project.name}/build/changelog.txt")
    def releaseType = isFabric ? project.findProperty('fabricVersionType') : project.findProperty('versionType')

    afterEvaluate {
        def publishMcVersion = isFabric ? fabric_minecraft_version : minecraft_version
        publishMods {
            file = jar.archiveFile
            displayName = "${mod_name.replace(' ','')}-${loaderName}-${publishMcVersion} ${project.mod_version}"
            println(displayName)
            if (changelogFile.exists()) {
                changelog.set(changelogFile.getText())
            }
            type = releaseType?.toUpperCase() ?: 'RELEASE'
            if (isFabric) {
                modLoaders.add("fabric")
                modLoaders.add("quilt")
            } else {
                modLoaders.add("neoforge")
            }
            curseforge {
                projectId = "252818"
                projectSlug = "dynamictrees"
                accessToken = providers.gradleProperty("curseApiKey").getOrElse(providers.environmentVariable("CURSEFORGE_API_KEY").getOrNull())
                minecraftVersions.add(publishMcVersion)
                if (isFabric) {
                    requires("forge-config-api-port")
                } else {
                    optional("dynamictreesplus")
                }
            }
            modrinth {
                projectId = "vdjF5PL5"
                accessToken = providers.gradleProperty("modrinthToken").getOrElse(providers.environmentVariable("MODRINTH_TOKEN").getOrNull())
                minecraftVersions.add(publishMcVersion)
                if (isFabric) {
                    requires("ohNO6lps")
                } else {
                    optional("qaO9Dqpu")
                }
            }
        }
    }
}

