# Important Notes:
# Every field you add must be added to the expandProps map in
# buildSrc/src/main/groovy/multiloader-common.gradle.

# Project
mod_name=Dynamic Trees
mod_author=Ferreusveritas
mod_id=dynamictrees
credits=Current developer: MaxHyper. Development of treepacks: Harley O'Connor. Help with version ports: Nyfaria, SizeableShrimp & Harley O'Connor
license=MIT
description=Trees that grow, forests that spread...
group=com.dtteam.dynamictrees
mod_version=1.9.0
fabricVersionAppend=-BETA
neoVersionAppend=-BETA
versionType=beta
fabricVersionType=beta

# Common / both loaders
minecraft_version=26.2
minecraft_version_range=[26.2]
## Vanilla compile target for :common. See https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2
java_version=25

# Fabric
fabric_version=0.158.0+26.2
fabric_loader_version=0.19.3

# Forge // Unused
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=26.2.0.59
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
forge_config_api_port_version=26.2.1
