# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
mod_name=Dynamic Trees
mod_author=Ferreusveritas
mod_id=dynamictrees
credits=Current developer: MaxHyper. Development of treepacks: Harley O'Connor. Help with version ports: Nyfaria, SizeableShrimp & Harley O'Connor
license=MIT
description=Trees that grow, forests that spread...
group=com.dtteam.dynamictrees
version=1.8.0
neoVersionType=beta
fabricVersionType=beta
neoVersionAppend=-BETA01
fabricVersionAppend=-BETA01

# Common
java_version=25
minecraft_version=26.1.1
minecraft_version_range=[26.1.1, 26.2)
neo_form_version=26.1.1-1
forge_config_api_port_version=26.1.3

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.145.3+26.1.1
fabric_loader_version=0.18.6
loom_version=1.9.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.1.1-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
