# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
mod_name=Dynamic Trees
mod_author=Ferreusveritas
mod_id=dynamictrees
credits=Current developer: MaxHyper. Development of treepacks: Harley O'Connor. Help with version ports: Nyfaria, SizeableShrimp & Harley O'Connor
license=MIT
description=Trees that grow, forests that spread...
version=1.6.0-BETA01
group=com.dtteam.dynamictrees

versionType=beta

# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10
java_version=21

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9

# Forge // Unused
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
