@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.dtteam.dynamictrees.deserialization;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;