@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.ferreusveritas.dynamictrees.block.branch;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;