@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.dtteam.dynamictrees.api.configuration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;