@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.ferreusveritas.dynamictrees.api.configurations;

import mezz.jei.api.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;