@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.ferreusveritas.dynamictrees.api.configuration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;