@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.ferreusveritas.dynamictrees.model.baked;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;