plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    id 'java'
    id 'idea'
    id 'maven-publish'
    id 'com.matthewprenger.cursegradle' version "1.4.0"
    id 'com.modrinth.minotaur' version "2.8.+"
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    sourceSets.main.resources {
        srcDir("src/generated/resources")
        srcDir("src/localization/resources")
    }

    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.files

}

//var changelogFile = file("temp/changelog.txt")
//
//subprojects {
//    publishing {
//        curseforge {
//            curseApiKey = optionalProperty("curseApiKey") ?: System.getenv("CURSEFORGE_API_KEY")
//            if (curseApiKey == null) {
//                project.logger.warn("API Key for CurseForge not detected; uploading will be disabled.")
//                return
//            }
//            apiKey = curseApiKey
//
//            project {
//                id = "252818"
//
//                addGameVersion(minecraft_version)
//
//                changelog = changelogFile
//                changelogType = "markdown"
//                releaseType = optionalProperty("versionType") ?: "release"
//
//                addArtifact(tasks.named("sourcesJar"))
//
//                mainArtifact(tasks.named("jar")) {
//                    relations {
//                        optionalDependency("dynamictreesplus")
//                    }
//                }
//            }
//        }
//
//        modrinth {
//            modrinthToken = optionalProperty("modrinthToken") ?: System.getenv("MODRINTH_TOKEN")
//            if (modrinthToken == null) {
//                project.logger.warn("Token for Modrinth not detected; uploading will be disabled.")
//                return
//            }
//
//            token.set(modrinthToken)
//            projectId.set(mod_id)
//            versionNumber.set("$minecraft_version-$version")
//            versionType.set(optionalProperty("versionType") ?: "release")
//            uploadFile.set(tasks.jar)
//            gameVersions.add(minecraft_version)
//            dependencies {
//                optional.project "dynamictreesplus"
//            }
//            if (changelogFile.exists()) {
//                changelog.set(changelogFile.toString())
//            }
//        }
//    }
//}
//
//def optionalProperty(String key) {
//    return project.findProperty(key)?.toString()
//}
