import me.modmuss50.mpp.ReleaseType

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    def mainResources = project(":common").file("src/main/resources")
    def genResources = project(":common").file("src/generated/resources")
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()
            programArgument ('--all')
            programArgument ('--existing')
            programArgument (mainResources.absolutePath)
            programArgument ('--output')
            programArgument (genResources.absolutePath)
            programArgument ('--mod')
            programArgument ("${mod_id}")
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
    repositories {
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
        flatDir {
            dir 'libs'
        }
    }
    dependencies {
        implementation "curse.maven:jade-324717:6011258"
        implementation "curse.maven:jei-238222:5846880"

        implementation "curse.maven:glitchcore-955399:5660740"
        implementation "curse.maven:serene-seasons-291874:5753503"
        implementation "curse.maven:patchouli-306770:6164617"
    }

    publishing {
        repositories {
            maven {
                url "file://${project.projectDir}/repo"
            }
            var mavenUsername = project.findProperty("harleyOConnorMavenUsername")?.toString() ?: System.getenv("MAVEN_USERNAME")
            var mavenPassword = project.findProperty("harleyOConnorMavenPassword")?.toString() ?: System.getenv("MAVEN_PASSWORD")
            if (mavenUsername == null || mavenPassword == null) {
                logger.log(LogLevel.WARN,"Credentials for maven not detected; it will be disabled.")
                return
            }
            maven {
                name = "HarleyOConnor"
                url = "https://harleyoconnor.com/maven"
                credentials {
                    username = mavenUsername
                    password = mavenPassword
                }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

def changelogFile = file("build/changelog.txt")

publishMods {
    file = jar.archiveFile
    displayName = "${mod_name.replace(' ','')}-NeoForge-${minecraft_version} ${project.version}"
    if (changelogFile.exists()) {
        changelog.set(changelogFile.getText())
    }
    type = ReleaseType.of(versionType.toUpperCase())
    modLoaders.add("neoforge")

    curseforge {
        projectId = "252818"
        projectSlug = "dynamictrees" // Required for discord webhook
        accessToken = curseApiKey ?: System.getenv("CURSEFORGE_API_KEY")
        minecraftVersions.add("1.21.1")
        optional("dynamictreesplus")
    }
    modrinth {
        projectId = "vdjF5PL5"
        accessToken = modrinthToken ?: System.getenv("MODRINTH_TOKEN")
        minecraftVersions.add("1.21.1")
        optional("qaO9Dqpu")
    }
}