plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id "me.modmuss50.mod-publish-plugin"
}
mod_version = "${mod_version}${neoVersionAppend}"
version = mod_version

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    def mainResources = project(":common").file("src/main/resources")
    def genClientResources = project(":common").file("src/generated/client/resources")
    def genServerResources = project(":common").file("src/generated/server/resources")
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        serverData {
            serverData()
            programArguments.addAll '--mod', "${mod_id}", '--all', '--output', genServerResources.absolutePath, '--existing', mainResources.absolutePath
        }
        clientData {
            clientData()
            programArguments.addAll '--mod', "${mod_id}", '--all', '--output', genClientResources.absolutePath, '--existing', mainResources.absolutePath
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
    repositories {
        maven {
            url "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
        maven {
            url "https://api.modrinth.com/maven"
            content {
                includeGroup "maven.modrinth"
            }
        }
        maven {
            name = "BlameJared"
            url = "https://maven.blamejared.com"
        }
        flatDir {
            dir 'libs'
        }
    }
    dependencies {
        implementation "maven.modrinth:jade:uGgaQ65p"
        implementation "mezz.jei:jei-26.2-neoforge:30.24.0.176"
        implementation "maven.modrinth:glitchcore:POAebwFo"
        implementation "maven.modrinth:serene-seasons:h9W9TVDe"
        implementation "net.jodah:typetools:0.6.3"
    }

}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.named('compileJava', JavaCompile) {
    options.compilerArgs << '-Xmaxerrs' << '10000'
}
