@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.ferreusveritas.dynamictrees.api;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;