@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.ferreusveritas.dynamictrees.api;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;