@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.ferreusveritas.dynamictrees.trees;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;