@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.dtteam.dynamictrees.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;