@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package com.ferreusveritas.dynamictrees.block;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;