@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package com.ferreusveritas.dynamictrees.models.baked;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;